"use client";

import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { persistor, RootState, store } from "@/reducer/store";
import { Store } from "@reduxjs/toolkit";
import { ToastContainer } from "react-toastify";
import "remixicon/fonts/remixicon.css";
import { Toaster } from "@/components/ui/sonner";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider store={store as Store<RootState>}>
          <PersistGate loading={null} persistor={persistor}>
            {children}
            <Toaster />
            <ToastContainer />
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
